language: node_js
node_js:
- '0.10'
before_install:
  - openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in config.tar.enc -out config.tar -d
  - tar xvf config.tar
install: npm install
env:
  global:
