language: node_js
node_js:
- '0.10'
before_install:
  - openssl aes-256-cbc -K $encrypted_b35871c9d9b5_key -iv $encrypted_b35871c9d9b5_iv -in config.tar.enc -out config.tar -d
  - tar xvf config.tar
install: npm install
env:
  global:
